name: Nix build
on:
  push:
    branches: [ "*" ]
jobs:
  build:
    name: Nix build
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job: [ { os: ubuntu-latest } ] # { os: macos-latest }
    steps:
    - uses: actions/checkout@v2
    - name: "Install Nix"
      uses: cachix/install-nix-action@v16
      with:
        nix_path: "nixpkgs=${{ steps.pinned_nixpkgs.outputs.url }}"
    - name: "Build packages"
      run: |
          nix-channel --add https://nixos.org/channels/nixos-21.11 nixpkgs
          nix-channel --update
          export NIX_PATH=$HOME/.nix-defexpr/channels${NIX_PATH:+:}$NIX_PATH
          nix-build
